name: Deploy to Amazon EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build, tag and push image to Docker Hub
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t datdh2024/store-repo:$IMAGE_TAG .
          docker push datdh2024/store-repo:$IMAGE_TAG
          echo "::set-output name=image::datdh2024/store-repo:$IMAGE_TAG"

      - name: Install Kubectl
        uses: azure/setup-kubectl@v1

      - name: Update kubectl context
        run: |
          aws eks --region ap-southeast-1 update-kubeconfig --name adorable-sheepdog-1740457536

      - name: Deploy to Amazon EKS
        run: |
          kubectl set image deployment store store=${{ steps.build-image.outputs.image }}
